# Generated by Django 2.2.5 on 2019-12-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Mywork')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Projects')),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('slug', models.SlugField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MyWork')),
            ],
        ),
    ]
